export const sampledata = [
    {
        "id": 1,
        "comments": "No lo vi pero deje mi info. Va los martes y jueves. Tienen mucho Humana",
        "visita": "4/30/19",
        "first_name": "Ajaib Mann",
        "last_name": "",
        "pic": "",
        "specialty": "IM",
        "company": "Genesis",
        "address": "Belle Terre 3000 N University Dr. Suite R, Coral Springs, FL 33065",
        "address2": "",
        "phone": "954-7530300",
        "mobile": "",
        "fax": "954-345-9340",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 2,
        "comments": "Gordito buena gente, tiene un paciente con melanoma que me lo va a enviar",
        "visita": "4/30/19",
        "first_name": "Gupta",
        "last_name": "",
        "pic": "",
        "specialty": "Dermatology",
        "company": "Advanced Dermatology",
        "address": "Coconut Square 4970 West Atlantic Blvd., Margate, FL 33063",
        "address2": "",
        "phone": "954-977-0270",
        "mobile": "",
        "fax": "954-977-6824",
        "email": "advancedderm.com",
        "hrs": "",
        "address3": "",
        "plan": "https://docs.google.com/document/d/15xFwiyQLCYDmhAwCpivcAHFiG-X0d-GmcivzBUi8x98",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 3,
        "comments": "oficina ocupada, secretarias tomaron mi info",
        "visita": "4/30/19",
        "first_name": "no dieron tarjeta",
        "last_name": "",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "Belle Terre 3000 N University Dr. Suite N, Coral Springs, FL 33065",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 4,
        "comments": "",
        "visita": "",
        "first_name": "David Fink, DO",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "n/a",
        "address": "5430 W Sample Rd, Margate, FL 33073",
        "address2": "",
        "phone": "(954) 320-3303",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 5,
        "comments": "",
        "visita": "",
        "first_name": "Gupta Neena",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "",
        "address": "5596 W Sample Rd, Margate, FL 33073",
        "address2": "",
        "phone": "(954) 968-4000",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 6,
        "comments": "",
        "visita": "",
        "first_name": "Vasanthi Chandrasekaran,",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "Margate Family Medical Center",
        "address": "Wrong address on web ",
        "address2": "",
        "phone": "(954) 956-7979",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "M-F:8-5; Sat:9-12:30",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 7,
        "comments": "Deje info con secretarias buena gente. ",
        "visita": "5/8/19",
        "first_name": "DeMarchi",
        "last_name": "",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "8190 Royal Palm Blvd #202, Pompano Beach, FL 33065",
        "address2": "",
        "phone": "(954) 753-7300",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "Thursday:9-5; Mon: 9-12",
        "address3": "",
        "plan": "5/19 recibi paciente! no he agradecido aun.",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 8,
        "comments": "mande carta. Left info when Dr Schwartz (5/19) was there but was busy. Spoke w Dr. Cohen about a mutual pt on 11/16/2020, gave my cel",
        "visita": "5/9/19; pero hable por telefono 11/16/2020",
        "first_name": "Dr. Alex R. ",
        "last_name": "Cohen",
        "pic": "",
        "specialty": "Family, DO",
        "company": "",
        "address": "1316 FL-7, Pompano Beach, FL 33063 ",
        "address2": "",
        "phone": "(954) 968-9993",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "Coconut Creek Pkwy, Margate, FL 33063",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 9,
        "comments": "",
        "visita": "wrong address",
        "first_name": "Schwarz Ross J MD",
        "last_name": "",
        "pic": "",
        "specialty": "IM?",
        "company": "",
        "address": "1316 FL-7, Margate, FL wrong address",
        "address2": "",
        "phone": "(954) 968-9993",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 10,
        "comments": "Lo conocí, AA, tiene Humana, buena gente, dijo que me enviaría pacientes!",
        "visita": "5/8/19",
        "first_name": "conoci a Dr Augustin ",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "",
        "address": "100 US-441 #301B, Margate, FL 33063",
        "address2": "",
        "phone": "(954) 933-9090",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 11,
        "comments": "Conocí a su PA Ramos, señora buena gente",
        "visita": "5/8/19",
        "first_name": "Arguello",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "en el edificio de Dr. Augustin, otra oficina",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 12,
        "comments": "Me envian pacientes, hay que enviar agradecimiento",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "DaVita Medical Group",
        "address": "9750 NW 33rd St Suite 212, Coral Springs, FL 33065 ",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 13,
        "comments": "Left cards w nice clerk, said needs more cards (9/4/2020)!",
        "visita": "9/4/20",
        "first_name": "Simon Wong, DO ",
        "last_name": "",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "9750 NW 33rd St #210, Coral Springs, FL 33065",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 14,
        "comments": "",
        "visita": "",
        "first_name": "Bridget Silva, MD",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "10220 W Sample Rd, Coral Springs, FL 33065",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 15,
        "comments": "",
        "visita": "",
        "first_name": "Averbuch Philip",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "9750 NW 33rd St Suite 116, Coral Springs, FL 33065",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 16,
        "comments": "",
        "visita": "",
        "first_name": "Luis Gutierrez/Coral",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "9690 W Sample Rd #101, Coral Springs, FL 33065",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 17,
        "comments": "Offi cerrada/quebrada!",
        "visita": "5/8/19",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "muchos IM y Family",
        "company": "Primary Care Physicians Of Florida",
        "address": "612 South State Road 7, Margate, FL 33068",
        "address2": "",
        "phone": "(954) 983-9191",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 18,
        "comments": "",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "Primary Care Physicians Of Florida",
        "address": "8880 Royal Palm Blvd Suite 105, Coral Springs, FL 33065",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 19,
        "comments": "Muy lejos, no visite",
        "visita": "5/8/19",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "no dicen medicos...",
        "company": "Primary Care Medical Center",
        "address": "",
        "address2": "",
        "phone": "(954) 533-2471",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 20,
        "comments": "Me envian pacientes, hay que enviar agradecimiento",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "no dicen medicos...",
        "company": "DaVita Medical Group",
        "address": "1401 N University Dr Suite 401, Coral Springs, FL 33071",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 21,
        "comments": "La conocí, buena gente ",
        "visita": "5/23/19",
        "first_name": "Kerr Sona ",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "",
        "address": "7975 W McNab Rd, Tamarac, FL 33321",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 22,
        "comments": "Ocupados, solo di mi info ",
        "visita": "5/23/19",
        "first_name": "Varios doctores",
        "last_name": "",
        "pic": "",
        "specialty": "Primary care, 2 or 3 MD’s",
        "company": "Clinical Care Medical Center",
        "address": "7495 N University Dr, Tamarac, FL 33321",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 23,
        "comments": "Hablé con office manager (Zulma), me dio tarjetas y pidió pacientes para clearance ",
        "visita": "5/23/19",
        "first_name": "Ronaldo Calonje",
        "last_name": "",
        "pic": "",
        "specialty": "Primary",
        "company": "",
        "address": "7401 N University Dr #206, Tamarac, FL 33321",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 24,
        "comments": "Mande carta. Deje info",
        "visita": "5/23/19/ hable con el por tel en 10/2020, luego de dejar info en su oficina de Tamarac. Buena gente. Tiene varias oficinas, hay que enviar info a todas",
        "first_name": "",
        "last_name": "Hecker",
        "pic": "",
        "specialty": "",
        "company": "Hecker Dermatology Group",
        "address": "7401 N University Dr, Suite 203, Tamarac  Tel: (954) 998-5105",
        "address2": "3500 NE 5th Avenue\nPompano Beach, FL 33064   Tel: (954) 998-5105",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 25,
        "comments": "La mayoría de pt no tienen seguro pero trataran de enviar pacientes",
        "visita": "5/28/19",
        "first_name": "varios médicos ",
        "last_name": "",
        "pic": "",
        "specialty": "Primary",
        "company": "CLINICA MEDICA HISPANA Medica ",
        "address": "8333 W McNab Rd #101, Tamarac, FL 33321",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "Abre a las 11 am ",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 26,
        "comments": "Creo que es uno de los 4 doctores de la clínica Hispana ",
        "visita": "5/28/19",
        "first_name": "Gabriel A. Sanchez, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Primary",
        "company": "",
        "address": "8333 W McNab Rd, Tamarac, FL 33321",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 27,
        "comments": "Secretaría dijo que me llamaría mañana",
        "visita": "5/28/19",
        "first_name": "Amy Roskin",
        "last_name": "",
        "pic": "",
        "specialty": "GYN",
        "company": "",
        "address": "833 West McNab road, suite 122, Tamarac, FL, 33321",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 28,
        "comments": "Paciente Roberty, Donnett, she came for a second opinion of her pelvic mass, will have sx w GYNONC (9/2020).",
        "visita": "",
        "first_name": "Barry Streit, MD",
        "last_name": "",
        "pic": "",
        "specialty": "pulmonary and cardiovascular?",
        "company": "assoc w Westside",
        "address": "6610 N University Dr, Tamarac, FL 33321",
        "address2": "",
        "phone": "954-720-6166",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 29,
        "comments": "pt Soffer, Edwards w back cyst and right skin lesion 9/2/20, came from ER though. Lft card w clerk. This is Optimo or something like that plan. He is with Dr. Penate and sent a patient",
        "visita": "9/4/2020",
        "first_name": "Amaury",
        "last_name": "Gomez",
        "pic": "",
        "specialty": "Family Medicine, DO",
        "company": "",
        "address": "9750 NW 33rd St #212, Coral Springs, FL, 33065",
        "address2": "",
        "phone": "954-755-5504",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 30,
        "comments": "Puerta cerrada, pase tarjetas por debajo 9/4/20.",
        "visita": "9/4/20",
        "first_name": "Ryan ",
        "last_name": "Kunstadt, MD",
        "pic": "",
        "specialty": "Endocrinologyst",
        "company": "",
        "address": "2901 Coral Hills Dr #150, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 753-0500",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 31,
        "comments": "",
        "visita": "",
        "first_name": "en nuestra ofi!",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "Westside Primary Care At Plantation",
        "address": "350 NW 84th Ave # 110, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 577-7277",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 32,
        "comments": "",
        "visita": "",
        "first_name": "Bennett?",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "Bennett Family Practice",
        "address": "201 NW 82nd Ave Ste 104, Plantation, FL 33324",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 33,
        "comments": "",
        "visita": "",
        "first_name": "Dr. Daniel McGee, D.O.",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "",
        "address": "201 NW 82nd Ave, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 577-2294",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 34,
        "comments": "",
        "visita": "",
        "first_name": "igual, muchos IM y family",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "Primary Care Physicians of Florida",
        "address": "West Side Medical Plaza, 8251 W Broward Blvd Suite 102, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 983-9191",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 35,
        "comments": "envia pacientes, hay que enviarle agradecimiento y tarjetas!",
        "visita": "",
        "first_name": "Isabel",
        "last_name": "Otero",
        "pic": "",
        "specialty": "GYN",
        "company": "",
        "address": "1200 N University Dr, Plantation, FL 33322",
        "address2": "",
        "phone": "(954) 474-2229",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 36,
        "comments": "",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "GI",
        "company": "West Broward Gastroenterology Associates, LLC, Digestive CARE",
        "address": "140 SW 84th Ave C, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 476-9350",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 37,
        "comments": "",
        "visita": "",
        "first_name": "Christine A. Davis-Fowler, Physician",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "",
        "address": "8430 W Broward Blvd Suite 200, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 533-5900",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "Monday - Friday: 9:00am - 6:00pm Saturday: 9:00am - 1:00pm",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 38,
        "comments": "",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "GYN",
        "company": "",
        "address": "140 SW 84th Ave Suite D, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 251-0431",
        "mobile": "",
        "fax": "",
        "email": "obgynwestbroward.com",
        "hrs": "m-f:8:30-5",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 39,
        "comments": "",
        "visita": "",
        "first_name": "Juan Carlos Zarza, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "Sanitas Medical Center - Plantation",
        "address": "180 SW 84th Ave, Plantation, FL 33324",
        "address2": "",
        "phone": "(844) 665-4827",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 40,
        "comments": "",
        "visita": "",
        "first_name": "Dr. Ramon L. Rivera-Olivieri, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "",
        "address": "180 SW 84th Ave, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 424-9300",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 41,
        "comments": "",
        "visita": "",
        "first_name": "Jane E. Matos-Fraebel, MD",
        "last_name": "",
        "pic": "",
        "specialty": "OBGYN",
        "company": "",
        "address": "220 SW 84th Ave #203, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 998-7760",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "m-f:9-5",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 42,
        "comments": "",
        "visita": "",
        "first_name": "Dr. Vakharia",
        "last_name": "",
        "pic": "",
        "specialty": "IM",
        "company": "Broward Community Medical Center",
        "address": "201 SW 84th Ave, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 741-7717",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 43,
        "comments": "",
        "visita": "",
        "first_name": "Sharma Ashok K MD",
        "last_name": "",
        "pic": "",
        "specialty": "Cardiologist",
        "company": "",
        "address": "260 SW 84th Ave A, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 382-0700",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "m-f:9-5",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 44,
        "comments": "",
        "visita": "",
        "first_name": "Dr. Michael R. Alexander, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Family",
        "company": "",
        "address": "7390 NW 5th St #2, Plantation, FL 33317",
        "address2": "",
        "phone": "(954) 424-9300",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 45,
        "comments": "",
        "visita": "",
        "first_name": "Dr. Ingrid Solomon, DO",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "6931 W Broward Blvd, Plantation, FL 33317",
        "address2": "",
        "phone": "(954) 321-5191",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 46,
        "comments": "tengo su cel, y mensajeamos, son buena gente",
        "visita": "",
        "first_name": "Mudit Jain, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Endocrinology",
        "company": "",
        "address": "300 NW 70th Ave #105, Plantation, FL 33317",
        "address2": "",
        "phone": "(954) 585-6292",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 47,
        "comments": "",
        "visita": "",
        "first_name": "Jeffrey Pollock, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Endocrinology",
        "company": "",
        "address": "201 Nw 82nd Ave, Plantation, FL, 33324",
        "address2": "",
        "phone": "(954) 617-0322",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 48,
        "comments": "",
        "visita": "",
        "first_name": "Carlos Vidalon, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Endocrinology",
        "company": "",
        "address": "201 Nw 82nd Ave, Plantation, FL, 33324",
        "address2": "",
        "phone": "(954) 625-6776",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 49,
        "comments": "Pt Shafer, Sheryl DOB: 11/15/1945, I saw in hospital but did as outpt.\n",
        "visita": "",
        "first_name": "Khan, Sabiha, MD",
        "last_name": "",
        "pic": "",
        "specialty": "IM",
        "company": "PGH and WS!",
        "address": "201 Nw 82nd Ave Ste 201 Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 236-3232",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 50,
        "comments": "",
        "visita": "",
        "first_name": "Alberto Fernandez, MD",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "201 Nw 82nd Ave, Plantation, FL, 33324",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 51,
        "comments": "tengo pt Moon, Madelyn, w 1ry HPT, and cough. No goiter (9/2020).",
        "visita": "visite 9/1/2020, deje info con secretaria. Called lft a mssg 9/4/20.",
        "first_name": "Andres Palacio, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Endocrinology",
        "company": "",
        "address": "3001 nw 49th ave., Fort Lauderdale, FL, 33313",
        "address2": "",
        "phone": "(954) 714-0684",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 52,
        "comments": "",
        "visita": "",
        "first_name": "Ikna Krysiak, DO",
        "last_name": "",
        "pic": "",
        "specialty": "Endocrinology",
        "company": "",
        "address": "3001 NW 49th Ave, Fort Lauderdale, FL, 33313",
        "address2": "",
        "phone": "(954) 474-5668",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 53,
        "comments": "called/thank office for his referal (didn't talk to him) told we'll give cards, 9/4/20.",
        "visita": "",
        "first_name": "Robin Saltz-PCP Associates",
        "last_name": "",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "350 NW 84th Ave suite 200 Plantation 33324",
        "address2": "",
        "phone": "954-424-4321",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 54,
        "comments": "pt Khan Dhanragee, renal disease GFR 32, PTH and calcium elevated, and an inferior lower gland on parathyroid scan (9/2020).",
        "visita": "",
        "first_name": "Vitra Gosine, MD",
        "last_name": "",
        "pic": "",
        "specialty": "Endocrinologist",
        "company": "954-800-1408",
        "address": "17900 NW 5th Street  Suite 202, Building K  Pembroke Pines, FL 33029",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "Ya enviamos tarjetas 10/2020",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 55,
        "comments": "good reputation",
        "visita": "",
        "first_name": "GLASSMAN, TODD",
        "last_name": "",
        "pic": "",
        "specialty": "Family medicine ",
        "company": "",
        "address": "16991 NE 20th Ave, North Miami Beach, FL 33162",
        "address2": "",
        "phone": "(305) 940-9300",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 56,
        "comments": "estoy en comunicacion con el por text",
        "visita": "",
        "first_name": "Wayne J ",
        "last_name": "Fraser",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "2331 N. State Rd 7 STE 201 Lauderhill, FL, 33313",
        "address2": "",
        "phone": "954-581-0088",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "Ya enviamos tarjetas 10/2020",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 57,
        "comments": "",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 58,
        "comments": "",
        "visita": "",
        "first_name": "David",
        "last_name": "Kahn, MD",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "South Florida Cancer Care",
        "address": "296 N. State Road 7, Suite 330 Margate, FL, 33063",
        "address2": "",
        "phone": "954-984-9998",
        "mobile": "",
        "fax": "954-984-9988",
        "email": "drkahn@southfloridacancercare.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "Ya enviamos tarjetas 10/2021",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 59,
        "comments": "estoy en comunicacion con el por text",
        "visita": "",
        "first_name": "Hepgur",
        "last_name": "Mehmet",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "201 East Sample Road, Deerfield Beach, FL 33064",
        "address2": "",
        "phone": "954-786-6660",
        "mobile": "",
        "fax": "954-786-7304",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "Podemos enviar tarjetas",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 60,
        "comments": "Deje tarjetas, pero ahora con un paciente en comun (Cunningham) podemos enviar mas)",
        "visita": "",
        "first_name": "Hari",
        "last_name": "Singh",
        "pic": "",
        "specialty": "GI",
        "company": "",
        "address": "2021 E Commercial Blvd Suite 202, Fort Lauderdale, FL, 33308",
        "address2": "",
        "phone": "954-202-7850",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 61,
        "comments": "1",
        "visita": "",
        "first_name": "Pamela",
        "last_name": "Rousseau",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "8035 W Oakland Park Blvd, Sunrise, FL 33351",
        "address2": "",
        "phone": "954-748-9196",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 62,
        "comments": "",
        "visita": "",
        "first_name": "Jeffrey J.",
        "last_name": "Kroll",
        "pic": "",
        "specialty": "Dermatology Group",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 63,
        "comments": "",
        "visita": "",
        "first_name": "Barry H. ",
        "last_name": "Dubner",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 64,
        "comments": "",
        "visita": "",
        "first_name": "Kimberly ",
        "last_name": "Hull",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 65,
        "comments": "",
        "visita": "",
        "first_name": "Nadine",
        "last_name": "Soro",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 66,
        "comments": "",
        "visita": "",
        "first_name": "Michael",
        "last_name": "Engelman",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 67,
        "comments": "",
        "visita": "",
        "first_name": "Barbara",
        "last_name": "Goldstein",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 68,
        "comments": "Impressionante oficina, super buena gente, me dio su cel, y ofrecio guiarme en poner practica privada!",
        "visita": "",
        "first_name": "Edward H.",
        "last_name": "Schlam",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "Jacaranda Professional Park, 10044 N.W. 1st Court, Plantation, FL 33324",
        "address2": "",
        "phone": "954-741-5600",
        "mobile": "305-527-8773",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 69,
        "comments": "",
        "visita": "",
        "first_name": "Richard",
        "last_name": "Rubenstein",
        "pic": "",
        "specialty": "Dermatology",
        "company": "Dermatology and Dermatologic Surgery",
        "address": "7421 N. University Drive, Suite 307, Tamarac, FL 33321",
        "address2": "",
        "phone": "954-720-7272",
        "mobile": "",
        "fax": "954-720-1878",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 70,
        "comments": "Hable con ella, gordita buena gente, deje tarjetas",
        "visita": "",
        "first_name": "Angela",
        "last_name": "Combs",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 71,
        "comments": "Me recomendaron hablar con 2 de ellos en su clinica de Coral Spring. Dr Saleeby will meet w me, this Friday?",
        "visita": "",
        "first_name": "Eli",
        "last_name": "Saleeby",
        "pic": "",
        "specialty": "Dermatology",
        "company": "Dermatology Consultants South Florida",
        "address": "1460 N University Dr, Coral Springs, FL 33071 1460 North  University Dr., Coral Spring, LF, 33071",
        "address2": "",
        "phone": "954-752-7552",
        "mobile": "",
        "fax": "954-752-4737",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "Lo conoci, señor buena gente, esta empezando a hacer estudios (research como PI) y me dijo que si tenia algo le dejara saber. Le deje tarjetas.",
        "marketing": "Le deje tarjetas 10/26/2020",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 72,
        "comments": "",
        "visita": "",
        "first_name": "Justin",
        "last_name": "Rubin",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 73,
        "comments": "Buena gente, deje tarjetas 10/2020.",
        "visita": "",
        "first_name": "Darron",
        "last_name": "Digiulio",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "Plantation",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 74,
        "comments": "conoci office manager, buena gente. 10/30/20",
        "visita": "",
        "first_name": "John",
        "last_name": "Grigg",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 75,
        "comments": "la conoci, buena gente, arribita de NW. 10/30/20",
        "visita": "",
        "first_name": "",
        "last_name": "Singh",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 76,
        "comments": "10/30/20. en la misma oficina de Dr. Singh, no estaba",
        "visita": "",
        "first_name": "",
        "last_name": "Vasanthi",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 77,
        "comments": "10/30/20. Le di tarjetas al staff, la Dra estaba de vacaciones",
        "visita": "",
        "first_name": "Doris",
        "last_name": "Hamawy",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 78,
        "comments": "10/30/20. La conoci, buena gente, envia pacientes al endosurgeon y a Dr Lago por ser subespecialistas.  Tiene pacientes Portugueses, y que hablan español.",
        "visita": "",
        "first_name": "Bridget",
        "last_name": "Silva",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "10220 W Sample Rd, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 340-1123",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 79,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Hepsharat",
        "last_name": "Amadi",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "10189 W Sample Rd, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 757-0064",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 80,
        "comments": "Entregue tarjetas en este urgent care 10/30/20",
        "visita": "enviaron pacientes 11/12/20 (Dr. Nawabi), y pidio mas tarjetas!",
        "first_name": "Naseh ",
        "last_name": "Nawabi",
        "pic": "",
        "specialty": "",
        "company": "Walking Urgent Care",
        "address": "10308 W Sample Rd, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 755-4880",
        "mobile": "",
        "fax": "",
        "email": "nawabi@hotmail.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 81,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Larry",
        "last_name": "Dolinsky",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "9900 W Sample Rd, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 709-6751",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 82,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Avinash Shiva",
        "last_name": "Persad",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "9750 NW 33rd St #220, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 217-3220",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 83,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Rosalyn",
        "last_name": "Amante",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "9750 NW 33rd St #220, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 217-3220",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 84,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Jose",
        "last_name": "Donatien",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "9750 NW 33rd St #105, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 320-3390",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 85,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Joshua",
        "last_name": "Rycus",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "9750 NW 33rd St #114, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 753-1477",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 86,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Carlos",
        "last_name": "Andrade",
        "pic": "",
        "specialty": "family Practice",
        "company": "",
        "address": "9690 W Sample Rd # 105, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 753-5550",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 87,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Leila",
        "last_name": "Morris",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "3100 Coral Hills Dr #303, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 575-3911",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 88,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Fine",
        "last_name": "Steven",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "3100 Coral Hills Dr, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 753-2754",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 89,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Steven",
        "last_name": "Foster",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "3100 Coral Hills Dr # 304, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 341-1007",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 90,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Victor",
        "last_name": "Gagno",
        "pic": "",
        "specialty": "Family NP",
        "company": "",
        "address": "3199 Coral Hills Dr APT 1, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 344-3000",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 91,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Vivienne",
        "last_name": "Tai",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "2929 N University Dr, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 346-5100",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 92,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Erik",
        "last_name": "Fernandez",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "2929 N University Dr Suite 104, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 889-3347",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 93,
        "comments": "10/30/20. Entregue mi tarjeta a staff",
        "visita": "",
        "first_name": "Luis",
        "last_name": "Gutierrez",
        "pic": "",
        "specialty": "",
        "company": "Primary Care Physicians of Florida-Coral Springs",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 94,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Meenu",
        "last_name": "Gupta",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 95,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Hady",
        "last_name": "Masri",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 96,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Serge",
        "last_name": "Gardere",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 97,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Elisa",
        "last_name": "Ginter",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 98,
        "comments": "No pase por su oficina",
        "visita": "",
        "first_name": "Hubert",
        "last_name": "Cantave",
        "pic": "",
        "specialty": "Family Medicine",
        "company": "",
        "address": "8880 Royal Palm Blvd #105, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 255-8128",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 99,
        "comments": "  ",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "OB-GYN",
        "company": "Comprehensive OG-GYN Coral Springs, FL",
        "address": "8880 Royal Palm Blvd Suite 100, Coral Springs, FL 33065",
        "address2": "",
        "phone": "(954) 753-2411",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 100,
        "comments": "10/04/20. Entregue mi tarjeta a staff",
        "visita": "",
        "first_name": "David",
        "last_name": "Herschthal",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "7280 W. Palmetto Park Rd. Boca Raton, FL 33433",
        "address2": "",
        "phone": "561-391-9200",
        "mobile": "",
        "fax": "",
        "email": "drherschthal.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 101,
        "comments": "10/04/20. Entregue mi tarjeta a staff",
        "visita": "",
        "first_name": "Jordana",
        "last_name": "Herschthal",
        "pic": "",
        "specialty": "Dermatology",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 102,
        "comments": "10/04/20. Entregue mi tarjeta a staff",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "Premier Derrmatology Partners-Lyons",
        "address": "20937 Lyons Rd, Boca Raton, FL 33428",
        "address2": "",
        "phone": "(561) 483-5666",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 103,
        "comments": "10/04/20. Entregue mi tarjeta a staff",
        "visita": "",
        "first_name": "Jodi",
        "last_name": "Diedler",
        "pic": "",
        "specialty": "",
        "company": "DermPartners",
        "address": "21019 FL-7 STE 120, Boca Raton, FL 33428",
        "address2": "",
        "phone": "(561) 883-5639",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 104,
        "comments": "10/04/20. Entregue mi tarjeta a staff",
        "visita": "",
        "first_name": "Shari",
        "last_name": "Topper",
        "pic": "",
        "specialty": "",
        "company": "DermPartners",
        "address": "21020 FL-7 STE 120, Boca Raton, FL 33428",
        "address2": "",
        "phone": "(561) 883-5640",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 105,
        "comments": "Mande carta. En text mssg con ella y su PA ",
        "visita": "Visite en 9/2020, deje tarjetas con staff pero no la vi",
        "first_name": "Andrea",
        "last_name": "Ramsay",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "8320 W Sunrise Blvd Ste 105 Plantation, FL 33322",
        "address2": "",
        "phone": "954-797-3887",
        "mobile": "954-478-4870",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 106,
        "comments": "En text mssg con ella y Dr. Ramsay, Andrea",
        "visita": "",
        "first_name": "Brittany",
        "last_name": "Cianelli",
        "pic": "",
        "specialty": "PA of Dr. Ramsay, Andrea",
        "company": "",
        "address": "8321 W Sunrise Blvd Ste 105 Plantation, FL 33322",
        "address2": "",
        "phone": "954-797-3888",
        "mobile": "954-465-8837",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 107,
        "comments": "",
        "visita": "",
        "first_name": "Lori",
        "last_name": "Frisard",
        "pic": "",
        "specialty": "",
        "company": "954-276-5552",
        "address": "305-562-9700",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 108,
        "comments": "",
        "visita": "",
        "first_name": "Roy",
        "last_name": "Bassett",
        "pic": "",
        "specialty": "",
        "company": "9544841710",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 109,
        "comments": "",
        "visita": "",
        "first_name": "",
        "last_name": "",
        "pic": "",
        "specialty": "",
        "company": "Primary Care Holistic Center",
        "address": "8050 N University Dr #103, Tamarac, FL 33321",
        "address2": "",
        "phone": "(954) 752-8888",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 110,
        "comments": "en text mssg con ella. Enviara pacientes de tiroides. Esta con Broward Health.",
        "visita": "",
        "first_name": "Soling",
        "last_name": "Li ",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "8890 W Oakland Park Blvd #203, Sunrise, FL 33351",
        "address2": "",
        "phone": "(954) 746-5678",
        "mobile": "9543193211",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 111,
        "comments": "Tengo pacientes en comun, deje mensajes telefonicos y enviamos cartas, 10/2020",
        "visita": "",
        "first_name": "Hugo",
        "last_name": "Fernandez",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "7189 Pembroke Rd, Pembroke Pines, FL 33023",
        "address2": "",
        "phone": "(954) 983-1220",
        "mobile": "",
        "fax": "",
        "email": "faxmg@primenetmedical.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 112,
        "comments": "Tengo pacientes en comun, deje mensajes telefonicos y enviamos cartas, 10/2021",
        "visita": "",
        "first_name": "",
        "last_name": "Casado",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "1100 S State Rd 7 Suite 104, Margate, FL 33068",
        "address2": "",
        "phone": "954-984-8000",
        "mobile": "",
        "fax": "",
        "email": "faxmg@primenetmedical.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 113,
        "comments": "no he visitado",
        "visita": "",
        "first_name": "Ronaldo",
        "last_name": "Calonje",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "7401 N University Dr #206, Tamarac, FL 33321",
        "address2": "",
        "phone": "(954) 718-2230",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 114,
        "comments": "no he visitado",
        "visita": "",
        "first_name": "William",
        "last_name": "Early",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "8302 W Oakland Park Blvd, Sunrise, FL 33351",
        "address2": "",
        "phone": "(954) 741-7577",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 115,
        "comments": "Mande carta. tengo pacientes en comun, llame y me recomendaron enviar un email, lo envie 10/2020",
        "visita": "",
        "first_name": "Jorge",
        "last_name": "Konopka",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "1951 Southwest 172nd Avenue\nSuite 312\nMiramar, FL 33029\n",
        "address2": "",
        "phone": "(954) 320-7999",
        "mobile": "",
        "fax": "",
        "email": "bckprimecareoffice@gmail.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 116,
        "comments": "",
        "visita": "",
        "first_name": "Satya",
        "last_name": "Singh",
        "pic": "",
        "specialty": "GI",
        "company": "",
        "address": "300 NW 70th Ave # 205, Plantation, FL 33317",
        "address2": "",
        "phone": "(954) 321-5428",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 117,
        "comments": "Hable con Alex, de Peru, buena gente, me dice que el Dr. Singh no hace ni hemorrhoides! Envio 2 pts 11/6/20! Enviar tarjetas nuevas!",
        "visita": "",
        "first_name": "Alex",
        "last_name": "Makezina",
        "pic": "",
        "specialty": "ARNP with Dr. Satya Singh GI",
        "company": "",
        "address": "300 NW 70th Ave # 205, Plantation, FL 33317",
        "address2": "",
        "phone": "(954) 321-5428",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 118,
        "comments": "Have a share patient sent to me by GI. Lft a mssg 11/20.  Will send a fax as requested on patients",
        "visita": "",
        "first_name": "Rona ",
        "last_name": "Mckenzie",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "1625 SE 3rd Ave, Fort Lauderdale, FL 33316",
        "address2": "",
        "phone": "(954) 832-0055",
        "mobile": "",
        "fax": "(954) 832-0262",
        "email": "info@mckos.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 119,
        "comments": "Have a share patient sent to me by GI. Lft a mssg 11/20.  Will send a fax as requested on patients",
        "visita": "",
        "first_name": "Wilfred",
        "last_name": "Mckenzie",
        "pic": "",
        "specialty": "IM, PCP",
        "company": "",
        "address": "1626 SE 3rd Ave, Fort Lauderdale, FL 33316",
        "address2": "",
        "phone": "(954) 832-0056",
        "mobile": "",
        "fax": "(954) 832-0263",
        "email": "info@mckos.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 120,
        "comments": "mande carta 1. Have a share patient. di tarjetas viejas, enviar nuevas!",
        "visita": "",
        "first_name": "Archana",
        "last_name": "Maini",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "Partners",
        "address": "1330 SE 4th Ave STE J, Fort Lauderdale, FL 33316",
        "address2": "",
        "phone": "(954) 623-7299",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 121,
        "comments": "Have a share patient. di tarjetas viejas, enviar nuevas!",
        "visita": "",
        "first_name": "Israel",
        "last_name": "Wiznitzer",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "8395 W. Oakland Park BLVD, Suite A, Sunrise, FL 33351",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 122,
        "comments": "",
        "visita": "",
        "first_name": "Khadra",
        "last_name": "Osman",
        "pic": "",
        "specialty": "GYN",
        "company": "",
        "address": "1625 SE 3rd Ave, Suite 400, Fort Lauderdale, FL 33316",
        "address2": "",
        "phone": "954-832-0055",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 123,
        "comments": "",
        "visita": "",
        "first_name": "Alvan",
        "last_name": "Khan",
        "pic": "",
        "specialty": "DO, PCP",
        "company": "",
        "address": "3702 Washington St, Hollywood, FL 33021",
        "address2": "",
        "phone": "(954) 967-6550",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 124,
        "comments": "Lo conoci en su oficina (muy grande). Un don buena gente, me dio su cel, me dijo que enviaria pacientes! Di tarjetas viejas, enviar nuevas!",
        "visita": "11/2020",
        "first_name": "Mohan",
        "last_name": "Gupta",
        "pic": "",
        "specialty": "Family Practice",
        "company": "",
        "address": "8396 W Oakland Park Blvd, Sunrise, FL 33351",
        "address2": "",
        "phone": "",
        "mobile": "954-817-0155",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 125,
        "comments": "",
        "visita": "",
        "first_name": "Medhat",
        "last_name": "Awad",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "8395 West Oakland Park Boulevard, Suite B, Sunrise, FL 33351",
        "address2": "",
        "phone": "954-578-2256",
        "mobile": "",
        "fax": "954-742-4630",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 126,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Chintan",
        "last_name": "Gandhi",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "7351 W Oakland Park Blvd Ste 101 Tamarac, FL 33319",
        "address2": "",
        "phone": "(954) 748-2500",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 127,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Sumit",
        "last_name": "Sawhney",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "7431 N University Dr #110, Tamarac, FL 33321",
        "address2": "",
        "phone": "(954) 726-0035",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 128,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Rohan",
        "last_name": "Faria",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "7432 N University Dr #110, Tamarac, FL 33321",
        "address2": "",
        "phone": "(954) 726-0036",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 129,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Alfred",
        "last_name": "Kalman",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "7433 N University Dr #110, Tamarac, FL 33321",
        "address2": "",
        "phone": "(954) 726-0037",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 130,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Jose",
        "last_name": "Melo",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "8200 W Sunrise Blvd Building C, Plantation, FL 33322",
        "address2": "",
        "phone": "(954) 370-8585",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 131,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Jason",
        "last_name": "Tache",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "8201 W Sunrise Blvd Building C, Plantation, FL 33322",
        "address2": "",
        "phone": "(954) 370-8586",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 132,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Harshad",
        "last_name": "Amin",
        "pic": "",
        "specialty": "Hem/onc",
        "company": "",
        "address": "8202 W Sunrise Blvd Building C, Plantation, FL 33322",
        "address2": "",
        "phone": "(954) 370-8587",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 133,
        "comments": "Lo conozco, no hay. que enviar carta",
        "visita": "",
        "first_name": "Israel",
        "last_name": "Penate",
        "pic": "",
        "specialty": "IM",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 134,
        "comments": "mande carta",
        "visita": "",
        "first_name": "Yaneth",
        "last_name": "Trujillo",
        "pic": "",
        "specialty": "MD, PCP",
        "company": "",
        "address": "1040 Weston Rd #215, Weston, FL 33326; but has office at Coral Springs, and Miramar",
        "address2": "",
        "phone": "(954) 436-8036",
        "mobile": "",
        "fax": "",
        "email": "info@trujillomedicalcenter.com",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 135,
        "comments": "Enviaron pt 11/2020",
        "visita": "",
        "first_name": "Amanda",
        "last_name": "Berg",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 136,
        "comments": "Enviaron pt 11/2021",
        "visita": "",
        "first_name": "",
        "last_name": "Spindler",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "",
        "address2": "",
        "phone": "",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 137,
        "comments": "mande carta. Have pt in common, texting w him. 10/2020",
        "visita": "",
        "first_name": "Rodolfo",
        "last_name": "Herrera",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "2929 N University Dr Ste 210 Coral Springs, FL 33065",
        "address2": "735 E Oakland Park Blvd Oakland Park, FL 33334",
        "phone": "954-757-1909",
        "mobile": "786-768-6434",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 138,
        "comments": "envie carta 2 con texto: letter saying:\r\nHe had a left breast bruising and hematoma that was palpable, currently it completely resolved so I would recommended him to continue monitoring his breasts and if an abnormality is noted, to come back for a repeat evaluation. ",
        "visita": "",
        "first_name": "Delt",
        "last_name": "Pierre",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "400 Executive Center Dr Ste 110\nWest Palm Beach, FL 33411",
        "address2": "",
        "phone": "(561) 429-2401",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 139,
        "comments": "envie carta",
        "visita": "",
        "first_name": "Victoria ",
        "last_name": "Perez",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "5355 Lyons Rd, Coconut Creek, FL 33073",
        "address2": "",
        "phone": "(954) 570-9595",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 140,
        "comments": "envie carta",
        "visita": "",
        "first_name": "Kim",
        "last_name": "Nickelson",
        "pic": "",
        "specialty": "PCP",
        "company": "",
        "address": "301 NW 84th Ave #101, Plantation, FL 33324",
        "address2": "",
        "phone": "(954) 581-1900",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 141,
        "comments": "envie carta con escrito especial",
        "visita": "",
        "first_name": "Mehmet",
        "last_name": "Hepgur",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "201 East Sample Road, Deerfield Beach, FL 33064\n",
        "address2": "",
        "phone": "Tel: 954-786-6660",
        "mobile": "Cel: 954-295-9390",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 142,
        "comments": "mande carta ",
        "visita": "",
        "first_name": "Raul ",
        "last_name": "Calderin",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "20215 NW 2nd Ave Ste 1\n\nMiami,FL,33169",
        "address2": "",
        "phone": "(305) 685-5688",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 143,
        "comments": "mande carta ",
        "visita": "",
        "first_name": "Baig",
        "last_name": "Mohammed",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "4100 S Hospital Dr, Plantation, FL 33317",
        "address2": "",
        "phone": "(954) 797-0601",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 144,
        "comments": "carta 1",
        "visita": "",
        "first_name": "Oscar",
        "last_name": "Mendez",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "2951 NW 49th Ave Ste 306, Lauderdale Lakes, FL, 33313",
        "address2": "",
        "phone": "(954) 717-4066",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 145,
        "comments": "mande carta",
        "visita": "",
        "first_name": "Brian",
        "last_name": "Polner",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "601 N Flamingo Rd, Pembroke Pines, FL 33028",
        "address2": "",
        "phone": "(954) 430-3866",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 146,
        "comments": "mande carta 2",
        "visita": "",
        "first_name": "Dennis",
        "last_name": "Spiller",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "3702 Washington St, Hollywood, FL 33021",
        "address2": "",
        "phone": "(954) 967-6550",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 147,
        "comments": "mande carta 1",
        "visita": "",
        "first_name": "Mark W",
        "last_name": " Kaylin",
        "pic": "",
        "specialty": "",
        "company": "",
        "address": "333 NW 70th Ave #107, Plantation, FL 33317",
        "address2": "",
        "phone": "(954) 581-0200",
        "mobile": "",
        "fax": "",
        "email": "",
        "hrs": "",
        "address3": "",
        "plan": "",
        "marketing": "",
        "created_at": null,
        "updated_at": null
    },
    {
        "id": 148,
        "comments": null,
        "visita": null,
        "first_name": null,
        "last_name": null,
        "pic": null,
        "specialty": null,
        "company": null,
        "address": null,
        "address2": null,
        "phone": null,
        "mobile": null,
        "fax": null,
        "email": null,
        "hrs": null,
        "address3": null,
        "plan": null,
        "marketing": null,
        "created_at": "2020-12-01T06:56:07.000000Z",
        "updated_at": "2020-12-01T06:56:07.000000Z"
    }
]

